// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type AckStatus int8

const (
	AckStatusUNKNOWN   AckStatus = 0
	AckStatusACCEPTED  AckStatus = 1
	AckStatusPERSISTED AckStatus = 2
)

var EnumNamesAckStatus = map[AckStatus]string{
	AckStatusUNKNOWN:   "UNKNOWN",
	AckStatusACCEPTED:  "ACCEPTED",
	AckStatusPERSISTED: "PERSISTED",
}

var EnumValuesAckStatus = map[string]AckStatus{
	"UNKNOWN":   AckStatusUNKNOWN,
	"ACCEPTED":  AckStatusACCEPTED,
	"PERSISTED": AckStatusPERSISTED,
}

func (v AckStatus) String() string {
	if s, ok := EnumNamesAckStatus[v]; ok {
		return s
	}
	return "AckStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
