// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AuthRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAuthRequest(buf []byte, offset flatbuffers.UOffsetT) *AuthRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AuthRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishAuthRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAuthRequest(buf []byte, offset flatbuffers.UOffsetT) *AuthRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AuthRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAuthRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AuthRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AuthRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AuthRequest) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AuthRequest) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AuthRequest) Platform() Platform {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return Platform(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *AuthRequest) MutatePlatform(n Platform) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *AuthRequest) AppVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AuthRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func AuthRequestAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func AuthRequestAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(deviceId), 0)
}
func AuthRequestAddPlatform(builder *flatbuffers.Builder, platform Platform) {
	builder.PrependInt8Slot(2, int8(platform), 0)
}
func AuthRequestAddAppVersion(builder *flatbuffers.Builder, appVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(appVersion), 0)
}
func AuthRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
