// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChatPush struct {
	_tab flatbuffers.Table
}

func GetRootAsChatPush(buf []byte, offset flatbuffers.UOffsetT) *ChatPush {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChatPush{}
	x.Init(buf, n+offset)
	return x
}

func FinishChatPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChatPush(buf []byte, offset flatbuffers.UOffsetT) *ChatPush {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChatPush{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChatPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChatPush) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChatPush) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChatPush) MsgId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatPush) SenderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatPush) SenderInfo(obj *UserInfo) *UserInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(UserInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChatPush) ChatType() ChatType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return ChatType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ChatPush) MutateChatType(n ChatType) bool {
	return rcv._tab.MutateInt8Slot(10, int8(n))
}

func (rcv *ChatPush) TargetId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatPush) MsgType() MsgType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return MsgType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ChatPush) MutateMsgType(n MsgType) bool {
	return rcv._tab.MutateInt8Slot(14, int8(n))
}

func (rcv *ChatPush) Content() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatPush) SendTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChatPush) MutateSendTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *ChatPush) Ext(obj *KeyValue, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ChatPush) ExtLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ChatPushStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func ChatPushAddMsgId(builder *flatbuffers.Builder, msgId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(msgId), 0)
}
func ChatPushAddSenderId(builder *flatbuffers.Builder, senderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(senderId), 0)
}
func ChatPushAddSenderInfo(builder *flatbuffers.Builder, senderInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(senderInfo), 0)
}
func ChatPushAddChatType(builder *flatbuffers.Builder, chatType ChatType) {
	builder.PrependInt8Slot(3, int8(chatType), 0)
}
func ChatPushAddTargetId(builder *flatbuffers.Builder, targetId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(targetId), 0)
}
func ChatPushAddMsgType(builder *flatbuffers.Builder, msgType MsgType) {
	builder.PrependInt8Slot(5, int8(msgType), 0)
}
func ChatPushAddContent(builder *flatbuffers.Builder, content flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(content), 0)
}
func ChatPushAddSendTime(builder *flatbuffers.Builder, sendTime int64) {
	builder.PrependInt64Slot(7, sendTime, 0)
}
func ChatPushAddExt(builder *flatbuffers.Builder, ext flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(ext), 0)
}
func ChatPushStartExtVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ChatPushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
