// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChatSendReq struct {
	_tab flatbuffers.Table
}

func GetRootAsChatSendReq(buf []byte, offset flatbuffers.UOffsetT) *ChatSendReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChatSendReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishChatSendReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChatSendReq(buf []byte, offset flatbuffers.UOffsetT) *ChatSendReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChatSendReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChatSendReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChatSendReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChatSendReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChatSendReq) ChatType() ChatType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ChatType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ChatSendReq) MutateChatType(n ChatType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *ChatSendReq) TargetId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatSendReq) MsgType() MsgType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return MsgType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ChatSendReq) MutateMsgType(n MsgType) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *ChatSendReq) Content() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatSendReq) Ext(obj *KeyValue, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ChatSendReq) ExtLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ChatSendReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ChatSendReqAddChatType(builder *flatbuffers.Builder, chatType ChatType) {
	builder.PrependInt8Slot(0, int8(chatType), 0)
}
func ChatSendReqAddTargetId(builder *flatbuffers.Builder, targetId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(targetId), 0)
}
func ChatSendReqAddMsgType(builder *flatbuffers.Builder, msgType MsgType) {
	builder.PrependInt8Slot(2, int8(msgType), 0)
}
func ChatSendReqAddContent(builder *flatbuffers.Builder, content flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(content), 0)
}
func ChatSendReqAddExt(builder *flatbuffers.Builder, ext flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(ext), 0)
}
func ChatSendReqStartExtVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ChatSendReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
