// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type ChatType int8

const (
	ChatTypeUNKNOWN ChatType = 0
	ChatTypePRIVATE ChatType = 1
	ChatTypeGROUP   ChatType = 2
	ChatTypeSYSTEM  ChatType = 3
	ChatTypeMAHJONG ChatType = 4
)

var EnumNamesChatType = map[ChatType]string{
	ChatTypeUNKNOWN: "UNKNOWN",
	ChatTypePRIVATE: "PRIVATE",
	ChatTypeGROUP:   "GROUP",
	ChatTypeSYSTEM:  "SYSTEM",
	ChatTypeMAHJONG: "MAHJONG",
}

var EnumValuesChatType = map[string]ChatType{
	"UNKNOWN": ChatTypeUNKNOWN,
	"PRIVATE": ChatTypePRIVATE,
	"GROUP":   ChatTypeGROUP,
	"SYSTEM":  ChatTypeSYSTEM,
	"MAHJONG": ChatTypeMAHJONG,
}

func (v ChatType) String() string {
	if s, ok := EnumNamesChatType[v]; ok {
		return s
	}
	return "ChatType(" + strconv.FormatInt(int64(v), 10) + ")"
}
