// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChatSendAck struct {
	_tab flatbuffers.Table
}

func GetRootAsChatSendAck(buf []byte, offset flatbuffers.UOffsetT) *ChatSendAck {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChatSendAck{}
	x.Init(buf, n+offset)
	return x
}

func FinishChatSendAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChatSendAck(buf []byte, offset flatbuffers.UOffsetT) *ChatSendAck {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChatSendAck{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChatSendAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChatSendAck) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChatSendAck) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChatSendAck) MsgId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatSendAck) SendTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChatSendAck) MutateSendTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func ChatSendAckStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ChatSendAckAddMsgId(builder *flatbuffers.Builder, msgId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(msgId), 0)
}
func ChatSendAckAddSendTime(builder *flatbuffers.Builder, sendTime int64) {
	builder.PrependInt64Slot(1, sendTime, 0)
}
func ChatSendAckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
