// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConversationReadReq struct {
	_tab flatbuffers.Table
}

func GetRootAsConversationReadReq(buf []byte, offset flatbuffers.UOffsetT) *ConversationReadReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConversationReadReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishConversationReadReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConversationReadReq(buf []byte, offset flatbuffers.UOffsetT) *ConversationReadReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConversationReadReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConversationReadReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConversationReadReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConversationReadReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConversationReadReq) PeerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationReadReq) GroupId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConversationReadReq) LastReadMsgId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConversationReadReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ConversationReadReqAddPeerId(builder *flatbuffers.Builder, peerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(peerId), 0)
}
func ConversationReadReqAddGroupId(builder *flatbuffers.Builder, groupId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(groupId), 0)
}
func ConversationReadReqAddLastReadMsgId(builder *flatbuffers.Builder, lastReadMsgId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(lastReadMsgId), 0)
}
func ConversationReadReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
