// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type ErrorCode int16

const (
	ErrorCodeSUCCESS        ErrorCode = 0
	ErrorCodeUNKNOWN_ERROR  ErrorCode = 1
	ErrorCodeAUTH_FAILED    ErrorCode = 1001
	ErrorCodePARAM_ERROR    ErrorCode = 1002
	ErrorCodeROOM_NOT_FOUND ErrorCode = 2001
	ErrorCodeROOM_FULL      ErrorCode = 2002
	ErrorCodeNOT_IN_ROOM    ErrorCode = 2003
)

var EnumNamesErrorCode = map[ErrorCode]string{
	ErrorCodeSUCCESS:        "SUCCESS",
	ErrorCodeUNKNOWN_ERROR:  "UNKNOWN_ERROR",
	ErrorCodeAUTH_FAILED:    "AUTH_FAILED",
	ErrorCodePARAM_ERROR:    "PARAM_ERROR",
	ErrorCodeROOM_NOT_FOUND: "ROOM_NOT_FOUND",
	ErrorCodeROOM_FULL:      "ROOM_FULL",
	ErrorCodeNOT_IN_ROOM:    "NOT_IN_ROOM",
}

var EnumValuesErrorCode = map[string]ErrorCode{
	"SUCCESS":        ErrorCodeSUCCESS,
	"UNKNOWN_ERROR":  ErrorCodeUNKNOWN_ERROR,
	"AUTH_FAILED":    ErrorCodeAUTH_FAILED,
	"PARAM_ERROR":    ErrorCodePARAM_ERROR,
	"ROOM_NOT_FOUND": ErrorCodeROOM_NOT_FOUND,
	"ROOM_FULL":      ErrorCodeROOM_FULL,
	"NOT_IN_ROOM":    ErrorCodeNOT_IN_ROOM,
}

func (v ErrorCode) String() string {
	if s, ok := EnumNamesErrorCode[v]; ok {
		return s
	}
	return "ErrorCode(" + strconv.FormatInt(int64(v), 10) + ")"
}
