// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type GameType int8

const (
	GameTypeUNKNOWN    GameType = 0
	GameTypeHT_MAHJONG GameType = 1
)

var EnumNamesGameType = map[GameType]string{
	GameTypeUNKNOWN:    "UNKNOWN",
	GameTypeHT_MAHJONG: "HT_MAHJONG",
}

var EnumValuesGameType = map[string]GameType{
	"UNKNOWN":    GameTypeUNKNOWN,
	"HT_MAHJONG": GameTypeHT_MAHJONG,
}

func (v GameType) String() string {
	if s, ok := EnumNamesGameType[v]; ok {
		return s
	}
	return "GameType(" + strconv.FormatInt(int64(v), 10) + ")"
}
