// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type GamePayload int8

const (
	GamePayloadNONE       GamePayload = 0
	GamePayloadMahjongReq GamePayload = 1
)

var EnumNamesGamePayload = map[GamePayload]string{
	GamePayloadNONE:       "NONE",
	GamePayloadMahjongReq: "MahjongReq",
}

var EnumValuesGamePayload = map[string]GamePayload{
	"NONE":       GamePayloadNONE,
	"MahjongReq": GamePayloadMahjongReq,
}

func (v GamePayload) String() string {
	if s, ok := EnumNamesGamePayload[v]; ok {
		return s
	}
	return "GamePayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
