// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GamePush struct {
	_tab flatbuffers.Table
}

func GetRootAsGamePush(buf []byte, offset flatbuffers.UOffsetT) *GamePush {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GamePush{}
	x.Init(buf, n+offset)
	return x
}

func FinishGamePushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGamePush(buf []byte, offset flatbuffers.UOffsetT) *GamePush {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GamePush{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGamePushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GamePush) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GamePush) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GamePush) RoomId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GamePush) GameType() GameType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return GameType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *GamePush) MutateGameType(n GameType) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *GamePush) GamePayloadType() GamePayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return GamePayload(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *GamePush) MutateGamePayloadType(n GamePayload) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *GamePush) GamePayload(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *GamePush) GamePayloadLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GamePush) GamePayloadBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GamePush) MutateGamePayload(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func GamePushStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func GamePushAddRoomId(builder *flatbuffers.Builder, roomId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(roomId), 0)
}
func GamePushAddGameType(builder *flatbuffers.Builder, gameType GameType) {
	builder.PrependInt8Slot(1, int8(gameType), 0)
}
func GamePushAddGamePayloadType(builder *flatbuffers.Builder, gamePayloadType GamePayload) {
	builder.PrependInt8Slot(2, int8(gamePayloadType), 0)
}
func GamePushAddGamePayload(builder *flatbuffers.Builder, gamePayload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(gamePayload), 0)
}
func GamePushStartGamePayloadVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func GamePushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
