// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type GameType int8

const (
	GameTypeUNKNOWN GameType = 0
	GameTypeMAHJONG GameType = 1
)

var EnumNamesGameType = map[GameType]string{
	GameTypeUNKNOWN: "UNKNOWN",
	GameTypeMAHJONG: "MAHJONG",
}

var EnumValuesGameType = map[string]GameType{
	"UNKNOWN": GameTypeUNKNOWN,
	"MAHJONG": GameTypeMAHJONG,
}

func (v GameType) String() string {
	if s, ok := EnumNamesGameType[v]; ok {
		return s
	}
	return "GameType(" + strconv.FormatInt(int64(v), 10) + ")"
}
