// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HeartbeatReq struct {
	_tab flatbuffers.Table
}

func GetRootAsHeartbeatReq(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeartbeatReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishHeartbeatReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHeartbeatReq(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HeartbeatReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHeartbeatReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HeartbeatReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeartbeatReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HeartbeatReq) ClientTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HeartbeatReq) MutateClientTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func HeartbeatReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HeartbeatReqAddClientTime(builder *flatbuffers.Builder, clientTime int64) {
	builder.PrependInt64Slot(0, clientTime, 0)
}
func HeartbeatReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
