// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HeartbeatResp struct {
	_tab flatbuffers.Table
}

func GetRootAsHeartbeatResp(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatResp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeartbeatResp{}
	x.Init(buf, n+offset)
	return x
}

func FinishHeartbeatRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHeartbeatResp(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatResp {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HeartbeatResp{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHeartbeatRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HeartbeatResp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeartbeatResp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HeartbeatResp) ServerTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HeartbeatResp) MutateServerTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func HeartbeatRespStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HeartbeatRespAddServerTime(builder *flatbuffers.Builder, serverTime int64) {
	builder.PrependInt64Slot(0, serverTime, 0)
}
func HeartbeatRespEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
