// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MahjongReq struct {
	_tab flatbuffers.Table
}

func GetRootAsMahjongReq(buf []byte, offset flatbuffers.UOffsetT) *MahjongReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MahjongReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishMahjongReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMahjongReq(buf []byte, offset flatbuffers.UOffsetT) *MahjongReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MahjongReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMahjongReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MahjongReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MahjongReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MahjongReq) Action() MahjongAction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return MahjongAction(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MahjongReq) MutateAction(n MahjongAction) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *MahjongReq) Tile(obj *MahjongTile) *MahjongTile {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MahjongTile)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MahjongReq) EventId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MahjongReq) DecisionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MahjongReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MahjongReqAddAction(builder *flatbuffers.Builder, action MahjongAction) {
	builder.PrependInt8Slot(0, int8(action), 0)
}
func MahjongReqAddTile(builder *flatbuffers.Builder, tile flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(tile), 0)
}
func MahjongReqAddEventId(builder *flatbuffers.Builder, eventId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(eventId), 0)
}
func MahjongReqAddDecisionId(builder *flatbuffers.Builder, decisionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(decisionId), 0)
}
func MahjongReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
