// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MahjongTile struct {
	_tab flatbuffers.Table
}

func GetRootAsMahjongTile(buf []byte, offset flatbuffers.UOffsetT) *MahjongTile {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MahjongTile{}
	x.Init(buf, n+offset)
	return x
}

func FinishMahjongTileBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMahjongTile(buf []byte, offset flatbuffers.UOffsetT) *MahjongTile {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MahjongTile{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMahjongTileBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MahjongTile) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MahjongTile) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MahjongTile) Color() MahjongColor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return MahjongColor(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MahjongTile) MutateColor(n MahjongColor) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *MahjongTile) Value() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MahjongTile) MutateValue(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *MahjongTile) Index() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MahjongTile) MutateIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func MahjongTileStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MahjongTileAddColor(builder *flatbuffers.Builder, color MahjongColor) {
	builder.PrependInt8Slot(0, int8(color), 0)
}
func MahjongTileAddValue(builder *flatbuffers.Builder, value int32) {
	builder.PrependInt32Slot(1, value, 0)
}
func MahjongTileAddIndex(builder *flatbuffers.Builder, index int32) {
	builder.PrependInt32Slot(2, index, 0)
}
func MahjongTileEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
