// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type MahjongColor int8

const (
	MahjongColorUNKNOWN MahjongColor = 0
	MahjongColorMAN     MahjongColor = 1
	MahjongColorSUO     MahjongColor = 2
	MahjongColorPIN     MahjongColor = 3
	MahjongColorHONORS  MahjongColor = 4
)

var EnumNamesMahjongColor = map[MahjongColor]string{
	MahjongColorUNKNOWN: "UNKNOWN",
	MahjongColorMAN:     "MAN",
	MahjongColorSUO:     "SUO",
	MahjongColorPIN:     "PIN",
	MahjongColorHONORS:  "HONORS",
}

var EnumValuesMahjongColor = map[string]MahjongColor{
	"UNKNOWN": MahjongColorUNKNOWN,
	"MAN":     MahjongColorMAN,
	"SUO":     MahjongColorSUO,
	"PIN":     MahjongColorPIN,
	"HONORS":  MahjongColorHONORS,
}

func (v MahjongColor) String() string {
	if s, ok := EnumNamesMahjongColor[v]; ok {
		return s
	}
	return "MahjongColor(" + strconv.FormatInt(int64(v), 10) + ")"
}
