// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type MahjongPushType int8

const (
	MahjongPushTypeNONE         MahjongPushType = 0
	MahjongPushTypeGameStart    MahjongPushType = 1
	MahjongPushTypeTurnChange   MahjongPushType = 2
	MahjongPushTypeActionResult MahjongPushType = 3
	MahjongPushTypeAskAction    MahjongPushType = 4
	MahjongPushTypeSettlement   MahjongPushType = 5
	MahjongPushTypeTotalResult  MahjongPushType = 6
)

var EnumNamesMahjongPushType = map[MahjongPushType]string{
	MahjongPushTypeNONE:         "NONE",
	MahjongPushTypeGameStart:    "GameStart",
	MahjongPushTypeTurnChange:   "TurnChange",
	MahjongPushTypeActionResult: "ActionResult",
	MahjongPushTypeAskAction:    "AskAction",
	MahjongPushTypeSettlement:   "Settlement",
	MahjongPushTypeTotalResult:  "TotalResult",
}

var EnumValuesMahjongPushType = map[string]MahjongPushType{
	"NONE":         MahjongPushTypeNONE,
	"GameStart":    MahjongPushTypeGameStart,
	"TurnChange":   MahjongPushTypeTurnChange,
	"ActionResult": MahjongPushTypeActionResult,
	"AskAction":    MahjongPushTypeAskAction,
	"Settlement":   MahjongPushTypeSettlement,
	"TotalResult":  MahjongPushTypeTotalResult,
}

func (v MahjongPushType) String() string {
	if s, ok := EnumNamesMahjongPushType[v]; ok {
		return s
	}
	return "MahjongPushType(" + strconv.FormatInt(int64(v), 10) + ")"
}
