// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type MahjongAction int8

const (
	MahjongActionDISCARD MahjongAction = 0
	MahjongActionPONG    MahjongAction = 1
	MahjongActionKONG    MahjongAction = 2
	MahjongActionHU      MahjongAction = 3
	MahjongActionZI_MO   MahjongAction = 4
	MahjongActionAUTO    MahjongAction = 5
	MahjongActionPASS    MahjongAction = 6
)

var EnumNamesMahjongAction = map[MahjongAction]string{
	MahjongActionDISCARD: "DISCARD",
	MahjongActionPONG:    "PONG",
	MahjongActionKONG:    "KONG",
	MahjongActionHU:      "HU",
	MahjongActionZI_MO:   "ZI_MO",
	MahjongActionAUTO:    "AUTO",
	MahjongActionPASS:    "PASS",
}

var EnumValuesMahjongAction = map[string]MahjongAction{
	"DISCARD": MahjongActionDISCARD,
	"PONG":    MahjongActionPONG,
	"KONG":    MahjongActionKONG,
	"HU":      MahjongActionHU,
	"ZI_MO":   MahjongActionZI_MO,
	"AUTO":    MahjongActionAUTO,
	"PASS":    MahjongActionPASS,
}

func (v MahjongAction) String() string {
	if s, ok := EnumNamesMahjongAction[v]; ok {
		return s
	}
	return "MahjongAction(" + strconv.FormatInt(int64(v), 10) + ")"
}
