// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MahjongPush struct {
	_tab flatbuffers.Table
}

func GetRootAsMahjongPush(buf []byte, offset flatbuffers.UOffsetT) *MahjongPush {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MahjongPush{}
	x.Init(buf, n+offset)
	return x
}

func FinishMahjongPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMahjongPush(buf []byte, offset flatbuffers.UOffsetT) *MahjongPush {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MahjongPush{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMahjongPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MahjongPush) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MahjongPush) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MahjongPush) EventId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MahjongPush) PushType() MahjongPushType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return MahjongPushType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MahjongPush) MutatePushType(n MahjongPushType) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *MahjongPush) PushData(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MahjongPush) PushDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MahjongPush) PushDataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MahjongPush) MutatePushData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func MahjongPushStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MahjongPushAddEventId(builder *flatbuffers.Builder, eventId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(eventId), 0)
}
func MahjongPushAddPushType(builder *flatbuffers.Builder, pushType MahjongPushType) {
	builder.PrependInt8Slot(1, int8(pushType), 0)
}
func MahjongPushAddPushData(builder *flatbuffers.Builder, pushData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(pushData), 0)
}
func MahjongPushStartPushDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MahjongPushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
