// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type MeldType int8

const (
	MeldTypePONG           MeldType = 0
	MeldTypeKONG           MeldType = 1
	MeldTypeCONCEALED_KONG MeldType = 2
	MeldTypeCHOW           MeldType = 3
)

var EnumNamesMeldType = map[MeldType]string{
	MeldTypePONG:           "PONG",
	MeldTypeKONG:           "KONG",
	MeldTypeCONCEALED_KONG: "CONCEALED_KONG",
	MeldTypeCHOW:           "CHOW",
}

var EnumValuesMeldType = map[string]MeldType{
	"PONG":           MeldTypePONG,
	"KONG":           MeldTypeKONG,
	"CONCEALED_KONG": MeldTypeCONCEALED_KONG,
	"CHOW":           MeldTypeCHOW,
}

func (v MeldType) String() string {
	if s, ok := EnumNamesMeldType[v]; ok {
		return s
	}
	return "MeldType(" + strconv.FormatInt(int64(v), 10) + ")"
}
