// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MeldGroup struct {
	_tab flatbuffers.Table
}

func GetRootAsMeldGroup(buf []byte, offset flatbuffers.UOffsetT) *MeldGroup {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MeldGroup{}
	x.Init(buf, n+offset)
	return x
}

func FinishMeldGroupBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMeldGroup(buf []byte, offset flatbuffers.UOffsetT) *MeldGroup {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MeldGroup{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMeldGroupBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MeldGroup) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MeldGroup) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MeldGroup) MeldType() MeldType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return MeldType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MeldGroup) MutateMeldType(n MeldType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *MeldGroup) Tiles(obj *MahjongTile, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MeldGroup) TilesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MeldGroup) FromSeat() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MeldGroup) MutateFromSeat(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func MeldGroupStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MeldGroupAddMeldType(builder *flatbuffers.Builder, meldType MeldType) {
	builder.PrependInt8Slot(0, int8(meldType), 0)
}
func MeldGroupAddTiles(builder *flatbuffers.Builder, tiles flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(tiles), 0)
}
func MeldGroupStartTilesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MeldGroupAddFromSeat(builder *flatbuffers.Builder, fromSeat int32) {
	builder.PrependInt32Slot(2, fromSeat, 0)
}
func MeldGroupEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
