// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MjActionResult struct {
	_tab flatbuffers.Table
}

func GetRootAsMjActionResult(buf []byte, offset flatbuffers.UOffsetT) *MjActionResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MjActionResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishMjActionResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMjActionResult(buf []byte, offset flatbuffers.UOffsetT) *MjActionResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MjActionResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMjActionResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MjActionResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MjActionResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MjActionResult) ActionSeat() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjActionResult) MutateActionSeat(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *MjActionResult) ActionUserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MjActionResult) Action() MahjongAction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return MahjongAction(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MjActionResult) MutateAction(n MahjongAction) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *MjActionResult) Tile(obj *MahjongTile) *MahjongTile {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MahjongTile)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MjActionResult) RelatedTiles(obj *MahjongTile, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MjActionResult) RelatedTilesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MjActionResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MjActionResultAddActionSeat(builder *flatbuffers.Builder, actionSeat int32) {
	builder.PrependInt32Slot(0, actionSeat, 0)
}
func MjActionResultAddActionUserId(builder *flatbuffers.Builder, actionUserId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(actionUserId), 0)
}
func MjActionResultAddAction(builder *flatbuffers.Builder, action MahjongAction) {
	builder.PrependInt8Slot(2, int8(action), 0)
}
func MjActionResultAddTile(builder *flatbuffers.Builder, tile flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(tile), 0)
}
func MjActionResultAddRelatedTiles(builder *flatbuffers.Builder, relatedTiles flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(relatedTiles), 0)
}
func MjActionResultStartRelatedTilesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MjActionResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
