// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MjAskAction struct {
	_tab flatbuffers.Table
}

func GetRootAsMjAskAction(buf []byte, offset flatbuffers.UOffsetT) *MjAskAction {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MjAskAction{}
	x.Init(buf, n+offset)
	return x
}

func FinishMjAskActionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMjAskAction(buf []byte, offset flatbuffers.UOffsetT) *MjAskAction {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MjAskAction{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMjAskActionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MjAskAction) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MjAskAction) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MjAskAction) DecisionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MjAskAction) Countdown() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjAskAction) MutateCountdown(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *MjAskAction) TriggerTile(obj *MahjongTile) *MahjongTile {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MahjongTile)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MjAskAction) AllowedActions(j int) MahjongAction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return MahjongAction(rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1)))
	}
	return 0
}

func (rcv *MjAskAction) AllowedActionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MjAskAction) MutateAllowedActions(j int, n MahjongAction) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt8(a+flatbuffers.UOffsetT(j*1), int8(n))
	}
	return false
}

func MjAskActionStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MjAskActionAddDecisionId(builder *flatbuffers.Builder, decisionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(decisionId), 0)
}
func MjAskActionAddCountdown(builder *flatbuffers.Builder, countdown int32) {
	builder.PrependInt32Slot(1, countdown, 0)
}
func MjAskActionAddTriggerTile(builder *flatbuffers.Builder, triggerTile flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(triggerTile), 0)
}
func MjAskActionAddAllowedActions(builder *flatbuffers.Builder, allowedActions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(allowedActions), 0)
}
func MjAskActionStartAllowedActionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MjAskActionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
