// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MjGameStart struct {
	_tab flatbuffers.Table
}

func GetRootAsMjGameStart(buf []byte, offset flatbuffers.UOffsetT) *MjGameStart {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MjGameStart{}
	x.Init(buf, n+offset)
	return x
}

func FinishMjGameStartBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMjGameStart(buf []byte, offset flatbuffers.UOffsetT) *MjGameStart {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MjGameStart{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMjGameStartBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MjGameStart) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MjGameStart) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MjGameStart) HandTiles(obj *MahjongTile, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MjGameStart) HandTilesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MjGameStart) PlayersPublicInfo(obj *PlayerPublicInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MjGameStart) PlayersPublicInfoLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MjGameStart) RemainCards() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjGameStart) MutateRemainCards(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *MjGameStart) DealerSeat() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjGameStart) MutateDealerSeat(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func MjGameStartStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MjGameStartAddHandTiles(builder *flatbuffers.Builder, handTiles flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(handTiles), 0)
}
func MjGameStartStartHandTilesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MjGameStartAddPlayersPublicInfo(builder *flatbuffers.Builder, playersPublicInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(playersPublicInfo), 0)
}
func MjGameStartStartPlayersPublicInfoVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MjGameStartAddRemainCards(builder *flatbuffers.Builder, remainCards int32) {
	builder.PrependInt32Slot(2, remainCards, 0)
}
func MjGameStartAddDealerSeat(builder *flatbuffers.Builder, dealerSeat int32) {
	builder.PrependInt32Slot(3, dealerSeat, 0)
}
func MjGameStartEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
