// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MjPlayerResult struct {
	_tab flatbuffers.Table
}

func GetRootAsMjPlayerResult(buf []byte, offset flatbuffers.UOffsetT) *MjPlayerResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MjPlayerResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishMjPlayerResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMjPlayerResult(buf []byte, offset flatbuffers.UOffsetT) *MjPlayerResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MjPlayerResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMjPlayerResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MjPlayerResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MjPlayerResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MjPlayerResult) Seat() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjPlayerResult) MutateSeat(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *MjPlayerResult) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MjPlayerResult) TotalScore() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjPlayerResult) MutateTotalScore(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *MjPlayerResult) WinCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjPlayerResult) MutateWinCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *MjPlayerResult) LoseCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjPlayerResult) MutateLoseCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func MjPlayerResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MjPlayerResultAddSeat(builder *flatbuffers.Builder, seat int32) {
	builder.PrependInt32Slot(0, seat, 0)
}
func MjPlayerResultAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(userId), 0)
}
func MjPlayerResultAddTotalScore(builder *flatbuffers.Builder, totalScore int32) {
	builder.PrependInt32Slot(2, totalScore, 0)
}
func MjPlayerResultAddWinCount(builder *flatbuffers.Builder, winCount int32) {
	builder.PrependInt32Slot(3, winCount, 0)
}
func MjPlayerResultAddLoseCount(builder *flatbuffers.Builder, loseCount int32) {
	builder.PrependInt32Slot(4, loseCount, 0)
}
func MjPlayerResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
