// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MjSettlement struct {
	_tab flatbuffers.Table
}

func GetRootAsMjSettlement(buf []byte, offset flatbuffers.UOffsetT) *MjSettlement {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MjSettlement{}
	x.Init(buf, n+offset)
	return x
}

func FinishMjSettlementBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMjSettlement(buf []byte, offset flatbuffers.UOffsetT) *MjSettlement {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MjSettlement{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMjSettlementBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MjSettlement) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MjSettlement) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MjSettlement) WinnerSeat() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjSettlement) MutateWinnerSeat(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *MjSettlement) WinType() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjSettlement) MutateWinType(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *MjSettlement) LoserSeat() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjSettlement) MutateLoserSeat(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *MjSettlement) ScoreChanges(j int) int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *MjSettlement) ScoreChangesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MjSettlement) MutateScoreChanges(j int, n int32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *MjSettlement) WinningTiles(obj *MahjongTile, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MjSettlement) WinningTilesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MjSettlement) FanDescription() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MjSettlement) FanCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjSettlement) MutateFanCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func MjSettlementStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func MjSettlementAddWinnerSeat(builder *flatbuffers.Builder, winnerSeat int32) {
	builder.PrependInt32Slot(0, winnerSeat, 0)
}
func MjSettlementAddWinType(builder *flatbuffers.Builder, winType int32) {
	builder.PrependInt32Slot(1, winType, 0)
}
func MjSettlementAddLoserSeat(builder *flatbuffers.Builder, loserSeat int32) {
	builder.PrependInt32Slot(2, loserSeat, 0)
}
func MjSettlementAddScoreChanges(builder *flatbuffers.Builder, scoreChanges flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(scoreChanges), 0)
}
func MjSettlementStartScoreChangesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MjSettlementAddWinningTiles(builder *flatbuffers.Builder, winningTiles flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(winningTiles), 0)
}
func MjSettlementStartWinningTilesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MjSettlementAddFanDescription(builder *flatbuffers.Builder, fanDescription flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(fanDescription), 0)
}
func MjSettlementAddFanCount(builder *flatbuffers.Builder, fanCount int32) {
	builder.PrependInt32Slot(6, fanCount, 0)
}
func MjSettlementEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
