// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MjTotalResult struct {
	_tab flatbuffers.Table
}

func GetRootAsMjTotalResult(buf []byte, offset flatbuffers.UOffsetT) *MjTotalResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MjTotalResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishMjTotalResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMjTotalResult(buf []byte, offset flatbuffers.UOffsetT) *MjTotalResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MjTotalResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMjTotalResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MjTotalResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MjTotalResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MjTotalResult) PlayerResults(obj *MjPlayerResult, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MjTotalResult) PlayerResultsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MjTotalResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MjTotalResultAddPlayerResults(builder *flatbuffers.Builder, playerResults flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(playerResults), 0)
}
func MjTotalResultStartPlayerResultsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MjTotalResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
