// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MjTurnChange struct {
	_tab flatbuffers.Table
}

func GetRootAsMjTurnChange(buf []byte, offset flatbuffers.UOffsetT) *MjTurnChange {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MjTurnChange{}
	x.Init(buf, n+offset)
	return x
}

func FinishMjTurnChangeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMjTurnChange(buf []byte, offset flatbuffers.UOffsetT) *MjTurnChange {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MjTurnChange{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMjTurnChangeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MjTurnChange) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MjTurnChange) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MjTurnChange) CurrentSeat() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjTurnChange) MutateCurrentSeat(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *MjTurnChange) RemainCards() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjTurnChange) MutateRemainCards(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *MjTurnChange) Countdown() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MjTurnChange) MutateCountdown(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *MjTurnChange) DrawnTile(obj *MahjongTile) *MahjongTile {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MahjongTile)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MjTurnChangeStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MjTurnChangeAddCurrentSeat(builder *flatbuffers.Builder, currentSeat int32) {
	builder.PrependInt32Slot(0, currentSeat, 0)
}
func MjTurnChangeAddRemainCards(builder *flatbuffers.Builder, remainCards int32) {
	builder.PrependInt32Slot(1, remainCards, 0)
}
func MjTurnChangeAddCountdown(builder *flatbuffers.Builder, countdown int32) {
	builder.PrependInt32Slot(2, countdown, 0)
}
func MjTurnChangeAddDrawnTile(builder *flatbuffers.Builder, drawnTile flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(drawnTile), 0)
}
func MjTurnChangeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
