// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type MsgType int8

const (
	MsgTypeUNKNOWN MsgType = 0
	MsgTypeTEXT    MsgType = 1
	MsgTypeIMAGE   MsgType = 2
	MsgTypeVOICE   MsgType = 3
	MsgTypeVIDEO   MsgType = 4
	MsgTypeFILE    MsgType = 5
	MsgTypeEMOJI   MsgType = 6
	MsgTypeCMD     MsgType = 7
)

var EnumNamesMsgType = map[MsgType]string{
	MsgTypeUNKNOWN: "UNKNOWN",
	MsgTypeTEXT:    "TEXT",
	MsgTypeIMAGE:   "IMAGE",
	MsgTypeVOICE:   "VOICE",
	MsgTypeVIDEO:   "VIDEO",
	MsgTypeFILE:    "FILE",
	MsgTypeEMOJI:   "EMOJI",
	MsgTypeCMD:     "CMD",
}

var EnumValuesMsgType = map[string]MsgType{
	"UNKNOWN": MsgTypeUNKNOWN,
	"TEXT":    MsgTypeTEXT,
	"IMAGE":   MsgTypeIMAGE,
	"VOICE":   MsgTypeVOICE,
	"VIDEO":   MsgTypeVIDEO,
	"FILE":    MsgTypeFILE,
	"EMOJI":   MsgTypeEMOJI,
	"CMD":     MsgTypeCMD,
}

func (v MsgType) String() string {
	if s, ok := EnumNamesMsgType[v]; ok {
		return s
	}
	return "MsgType(" + strconv.FormatInt(int64(v), 10) + ")"
}
