// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type Platform int8

const (
	PlatformUNKNOWN Platform = 0
	PlatformANDROID Platform = 1
	PlatformIOS     Platform = 2
	PlatformWEB     Platform = 3
	PlatformDESKTOP Platform = 4
	PlatformWECHAT  Platform = 5
)

var EnumNamesPlatform = map[Platform]string{
	PlatformUNKNOWN: "UNKNOWN",
	PlatformANDROID: "ANDROID",
	PlatformIOS:     "IOS",
	PlatformWEB:     "WEB",
	PlatformDESKTOP: "DESKTOP",
	PlatformWECHAT:  "WECHAT",
}

var EnumValuesPlatform = map[string]Platform{
	"UNKNOWN": PlatformUNKNOWN,
	"ANDROID": PlatformANDROID,
	"IOS":     PlatformIOS,
	"WEB":     PlatformWEB,
	"DESKTOP": PlatformDESKTOP,
	"WECHAT":  PlatformWECHAT,
}

func (v Platform) String() string {
	if s, ok := EnumNamesPlatform[v]; ok {
		return s
	}
	return "Platform(" + strconv.FormatInt(int64(v), 10) + ")"
}
