// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerPublicInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerPublicInfo(buf []byte, offset flatbuffers.UOffsetT) *PlayerPublicInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerPublicInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerPublicInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerPublicInfo(buf []byte, offset flatbuffers.UOffsetT) *PlayerPublicInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerPublicInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerPublicInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerPublicInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerPublicInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerPublicInfo) Seat() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerPublicInfo) MutateSeat(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *PlayerPublicInfo) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PlayerPublicInfo) Melds(obj *MeldGroup, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PlayerPublicInfo) MeldsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PlayerPublicInfo) Discarded(obj *MahjongTile, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PlayerPublicInfo) DiscardedLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PlayerPublicInfo) HandCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerPublicInfo) MutateHandCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func PlayerPublicInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PlayerPublicInfoAddSeat(builder *flatbuffers.Builder, seat int32) {
	builder.PrependInt32Slot(0, seat, 0)
}
func PlayerPublicInfoAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(userId), 0)
}
func PlayerPublicInfoAddMelds(builder *flatbuffers.Builder, melds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(melds), 0)
}
func PlayerPublicInfoStartMeldsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PlayerPublicInfoAddDiscarded(builder *flatbuffers.Builder, discarded flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(discarded), 0)
}
func PlayerPublicInfoStartDiscardedVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PlayerPublicInfoAddHandCount(builder *flatbuffers.Builder, handCount int32) {
	builder.PrependInt32Slot(4, handCount, 0)
}
func PlayerPublicInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
