// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type RequestPayload int8

const (
	RequestPayloadNONE         RequestPayload = 0
	RequestPayloadChatSendReq  RequestPayload = 1
	RequestPayloadGameReq      RequestPayload = 2
	RequestPayloadHeartbeatReq RequestPayload = 3
	RequestPayloadRoomReq      RequestPayload = 4
)

var EnumNamesRequestPayload = map[RequestPayload]string{
	RequestPayloadNONE:         "NONE",
	RequestPayloadChatSendReq:  "ChatSendReq",
	RequestPayloadGameReq:      "GameReq",
	RequestPayloadHeartbeatReq: "HeartbeatReq",
	RequestPayloadRoomReq:      "RoomReq",
}

var EnumValuesRequestPayload = map[string]RequestPayload{
	"NONE":         RequestPayloadNONE,
	"ChatSendReq":  RequestPayloadChatSendReq,
	"GameReq":      RequestPayloadGameReq,
	"HeartbeatReq": RequestPayloadHeartbeatReq,
	"RoomReq":      RequestPayloadRoomReq,
}

func (v RequestPayload) String() string {
	if s, ok := EnumNamesRequestPayload[v]; ok {
		return s
	}
	return "RequestPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
