// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type ResponsePayload int8

const (
	ResponsePayloadNONE          ResponsePayload = 0
	ResponsePayloadChatSendAck   ResponsePayload = 1
	ResponsePayloadRoomResp      ResponsePayload = 2
	ResponsePayloadHeartbeatResp ResponsePayload = 3
	ResponsePayloadChatPush      ResponsePayload = 10
	ResponsePayloadGamePush      ResponsePayload = 11
	ResponsePayloadRoomPush      ResponsePayload = 12
	ResponsePayloadSystemPush    ResponsePayload = 13
)

var EnumNamesResponsePayload = map[ResponsePayload]string{
	ResponsePayloadNONE:          "NONE",
	ResponsePayloadChatSendAck:   "ChatSendAck",
	ResponsePayloadRoomResp:      "RoomResp",
	ResponsePayloadHeartbeatResp: "HeartbeatResp",
	ResponsePayloadChatPush:      "ChatPush",
	ResponsePayloadGamePush:      "GamePush",
	ResponsePayloadRoomPush:      "RoomPush",
	ResponsePayloadSystemPush:    "SystemPush",
}

var EnumValuesResponsePayload = map[string]ResponsePayload{
	"NONE":          ResponsePayloadNONE,
	"ChatSendAck":   ResponsePayloadChatSendAck,
	"RoomResp":      ResponsePayloadRoomResp,
	"HeartbeatResp": ResponsePayloadHeartbeatResp,
	"ChatPush":      ResponsePayloadChatPush,
	"GamePush":      ResponsePayloadGamePush,
	"RoomPush":      ResponsePayloadRoomPush,
	"SystemPush":    ResponsePayloadSystemPush,
}

func (v ResponsePayload) String() string {
	if s, ok := EnumNamesResponsePayload[v]; ok {
		return s
	}
	return "ResponsePayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
