// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type RoomStatus int8

const (
	RoomStatusWAITING  RoomStatus = 0
	RoomStatusPLAYING  RoomStatus = 1
	RoomStatusSETTLING RoomStatus = 2
)

var EnumNamesRoomStatus = map[RoomStatus]string{
	RoomStatusWAITING:  "WAITING",
	RoomStatusPLAYING:  "PLAYING",
	RoomStatusSETTLING: "SETTLING",
}

var EnumValuesRoomStatus = map[string]RoomStatus{
	"WAITING":  RoomStatusWAITING,
	"PLAYING":  RoomStatusPLAYING,
	"SETTLING": RoomStatusSETTLING,
}

func (v RoomStatus) String() string {
	if s, ok := EnumNamesRoomStatus[v]; ok {
		return s
	}
	return "RoomStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
