// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type RoomAction int8

const (
	RoomActionCREATE RoomAction = 0
	RoomActionJOIN   RoomAction = 1
	RoomActionLEAVE  RoomAction = 2
	RoomActionREADY  RoomAction = 3
)

var EnumNamesRoomAction = map[RoomAction]string{
	RoomActionCREATE: "CREATE",
	RoomActionJOIN:   "JOIN",
	RoomActionLEAVE:  "LEAVE",
	RoomActionREADY:  "READY",
}

var EnumValuesRoomAction = map[string]RoomAction{
	"CREATE": RoomActionCREATE,
	"JOIN":   RoomActionJOIN,
	"LEAVE":  RoomActionLEAVE,
	"READY":  RoomActionREADY,
}

func (v RoomAction) String() string {
	if s, ok := EnumNamesRoomAction[v]; ok {
		return s
	}
	return "RoomAction(" + strconv.FormatInt(int64(v), 10) + ")"
}
