// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RoomInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsRoomInfo(buf []byte, offset flatbuffers.UOffsetT) *RoomInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RoomInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishRoomInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRoomInfo(buf []byte, offset flatbuffers.UOffsetT) *RoomInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RoomInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRoomInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RoomInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RoomInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RoomInfo) RoomId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RoomInfo) OwnerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RoomInfo) MaxPlayers() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RoomInfo) MutateMaxPlayers(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *RoomInfo) CurrentPlayers() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RoomInfo) MutateCurrentPlayers(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *RoomInfo) Players(obj *RoomPlayer, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RoomInfo) PlayersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RoomInfo) Status() RoomStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return RoomStatus(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *RoomInfo) MutateStatus(n RoomStatus) bool {
	return rcv._tab.MutateInt8Slot(14, int8(n))
}

func RoomInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func RoomInfoAddRoomId(builder *flatbuffers.Builder, roomId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(roomId), 0)
}
func RoomInfoAddOwnerId(builder *flatbuffers.Builder, ownerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(ownerId), 0)
}
func RoomInfoAddMaxPlayers(builder *flatbuffers.Builder, maxPlayers int32) {
	builder.PrependInt32Slot(2, maxPlayers, 0)
}
func RoomInfoAddCurrentPlayers(builder *flatbuffers.Builder, currentPlayers int32) {
	builder.PrependInt32Slot(3, currentPlayers, 0)
}
func RoomInfoAddPlayers(builder *flatbuffers.Builder, players flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(players), 0)
}
func RoomInfoStartPlayersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RoomInfoAddStatus(builder *flatbuffers.Builder, status RoomStatus) {
	builder.PrependInt8Slot(5, int8(status), 0)
}
func RoomInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
