// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RoomPlayer struct {
	_tab flatbuffers.Table
}

func GetRootAsRoomPlayer(buf []byte, offset flatbuffers.UOffsetT) *RoomPlayer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RoomPlayer{}
	x.Init(buf, n+offset)
	return x
}

func FinishRoomPlayerBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRoomPlayer(buf []byte, offset flatbuffers.UOffsetT) *RoomPlayer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RoomPlayer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRoomPlayerBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RoomPlayer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RoomPlayer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RoomPlayer) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RoomPlayer) User(obj *UserInfo) *UserInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(UserInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *RoomPlayer) IsReady() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *RoomPlayer) MutateIsReady(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *RoomPlayer) SeatIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RoomPlayer) MutateSeatIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *RoomPlayer) IsOnline() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *RoomPlayer) MutateIsOnline(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func RoomPlayerStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func RoomPlayerAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(userId), 0)
}
func RoomPlayerAddUser(builder *flatbuffers.Builder, user flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(user), 0)
}
func RoomPlayerAddIsReady(builder *flatbuffers.Builder, isReady bool) {
	builder.PrependBoolSlot(2, isReady, false)
}
func RoomPlayerAddSeatIndex(builder *flatbuffers.Builder, seatIndex int32) {
	builder.PrependInt32Slot(3, seatIndex, 0)
}
func RoomPlayerAddIsOnline(builder *flatbuffers.Builder, isOnline bool) {
	builder.PrependBoolSlot(4, isOnline, false)
}
func RoomPlayerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
