// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RoomReq struct {
	_tab flatbuffers.Table
}

func GetRootAsRoomReq(buf []byte, offset flatbuffers.UOffsetT) *RoomReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RoomReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishRoomReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRoomReq(buf []byte, offset flatbuffers.UOffsetT) *RoomReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RoomReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRoomReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RoomReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RoomReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RoomReq) Action() RoomAction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return RoomAction(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *RoomReq) MutateAction(n RoomAction) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *RoomReq) GameType() GameType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return GameType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *RoomReq) MutateGameType(n GameType) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *RoomReq) RoomId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RoomReq) RoomConfig() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RoomReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func RoomReqAddAction(builder *flatbuffers.Builder, action RoomAction) {
	builder.PrependInt8Slot(0, int8(action), 0)
}
func RoomReqAddGameType(builder *flatbuffers.Builder, gameType GameType) {
	builder.PrependInt8Slot(1, int8(gameType), 0)
}
func RoomReqAddRoomId(builder *flatbuffers.Builder, roomId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(roomId), 0)
}
func RoomReqAddRoomConfig(builder *flatbuffers.Builder, roomConfig flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(roomConfig), 0)
}
func RoomReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
