// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RoomPush struct {
	_tab flatbuffers.Table
}

func GetRootAsRoomPush(buf []byte, offset flatbuffers.UOffsetT) *RoomPush {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RoomPush{}
	x.Init(buf, n+offset)
	return x
}

func FinishRoomPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRoomPush(buf []byte, offset flatbuffers.UOffsetT) *RoomPush {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RoomPush{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRoomPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RoomPush) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RoomPush) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RoomPush) Event() RoomEvent {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return RoomEvent(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *RoomPush) MutateEvent(n RoomEvent) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *RoomPush) RoomId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RoomPush) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RoomPush) RoomInfo(obj *RoomInfo) *RoomInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(RoomInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RoomPushStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func RoomPushAddEvent(builder *flatbuffers.Builder, event RoomEvent) {
	builder.PrependInt8Slot(0, int8(event), 0)
}
func RoomPushAddRoomId(builder *flatbuffers.Builder, roomId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(roomId), 0)
}
func RoomPushAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(userId), 0)
}
func RoomPushAddRoomInfo(builder *flatbuffers.Builder, roomInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(roomInfo), 0)
}
func RoomPushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
