// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type RoomEvent int8

const (
	RoomEventUSER_JOINED    RoomEvent = 0
	RoomEventUSER_LEFT      RoomEvent = 1
	RoomEventUSER_READY     RoomEvent = 2
	RoomEventGAME_START     RoomEvent = 3
	RoomEventGAME_OVER      RoomEvent = 4
	RoomEventROOM_DISMISSED RoomEvent = 5
)

var EnumNamesRoomEvent = map[RoomEvent]string{
	RoomEventUSER_JOINED:    "USER_JOINED",
	RoomEventUSER_LEFT:      "USER_LEFT",
	RoomEventUSER_READY:     "USER_READY",
	RoomEventGAME_START:     "GAME_START",
	RoomEventGAME_OVER:      "GAME_OVER",
	RoomEventROOM_DISMISSED: "ROOM_DISMISSED",
}

var EnumValuesRoomEvent = map[string]RoomEvent{
	"USER_JOINED":    RoomEventUSER_JOINED,
	"USER_LEFT":      RoomEventUSER_LEFT,
	"USER_READY":     RoomEventUSER_READY,
	"GAME_START":     RoomEventGAME_START,
	"GAME_OVER":      RoomEventGAME_OVER,
	"ROOM_DISMISSED": RoomEventROOM_DISMISSED,
}

func (v RoomEvent) String() string {
	if s, ok := EnumNamesRoomEvent[v]; ok {
		return s
	}
	return "RoomEvent(" + strconv.FormatInt(int64(v), 10) + ")"
}
