// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SystemPush struct {
	_tab flatbuffers.Table
}

func GetRootAsSystemPush(buf []byte, offset flatbuffers.UOffsetT) *SystemPush {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SystemPush{}
	x.Init(buf, n+offset)
	return x
}

func FinishSystemPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSystemPush(buf []byte, offset flatbuffers.UOffsetT) *SystemPush {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SystemPush{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSystemPushBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SystemPush) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SystemPush) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SystemPush) Title() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SystemPush) Content() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SystemPush) Level() SystemLevel {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return SystemLevel(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SystemPush) MutateLevel(n SystemLevel) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *SystemPush) ActionUrl() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SystemPushStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func SystemPushAddTitle(builder *flatbuffers.Builder, title flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(title), 0)
}
func SystemPushAddContent(builder *flatbuffers.Builder, content flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(content), 0)
}
func SystemPushAddLevel(builder *flatbuffers.Builder, level SystemLevel) {
	builder.PrependInt8Slot(2, int8(level), 0)
}
func SystemPushAddActionUrl(builder *flatbuffers.Builder, actionUrl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(actionUrl), 0)
}
func SystemPushEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
