// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type SystemLevel int8

const (
	SystemLevelINFO    SystemLevel = 0
	SystemLevelWARNING SystemLevel = 1
	SystemLevelERROR   SystemLevel = 2
)

var EnumNamesSystemLevel = map[SystemLevel]string{
	SystemLevelINFO:    "INFO",
	SystemLevelWARNING: "WARNING",
	SystemLevelERROR:   "ERROR",
}

var EnumValuesSystemLevel = map[string]SystemLevel{
	"INFO":    SystemLevelINFO,
	"WARNING": SystemLevelWARNING,
	"ERROR":   SystemLevelERROR,
}

func (v SystemLevel) String() string {
	if s, ok := EnumNamesSystemLevel[v]; ok {
		return s
	}
	return "SystemLevel(" + strconv.FormatInt(int64(v), 10) + ")"
}
