// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsUserInfo(buf []byte, offset flatbuffers.UOffsetT) *UserInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishUserInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUserInfo(buf []byte, offset flatbuffers.UOffsetT) *UserInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUserInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UserInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserInfo) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UserInfo) Nickname() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UserInfo) Avatar() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UserInfo) Level() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UserInfo) MutateLevel(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *UserInfo) Coins() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UserInfo) MutateCoins(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func UserInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func UserInfoAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(userId), 0)
}
func UserInfoAddNickname(builder *flatbuffers.Builder, nickname flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(nickname), 0)
}
func UserInfoAddAvatar(builder *flatbuffers.Builder, avatar flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(avatar), 0)
}
func UserInfoAddLevel(builder *flatbuffers.Builder, level int32) {
	builder.PrependInt32Slot(3, level, 0)
}
func UserInfoAddCoins(builder *flatbuffers.Builder, coins int64) {
	builder.PrependInt64Slot(4, coins, 0)
}
func UserInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
