// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ChatType } from '../../im/protocol/chat-type.js';
import { KeyValue } from '../../im/protocol/key-value.js';
import { MsgType } from '../../im/protocol/msg-type.js';
import { UserInfo } from '../../im/protocol/user-info.js';


export class ChatPush {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatPush {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatPush(bb:flatbuffers.ByteBuffer, obj?:ChatPush):ChatPush {
  return (obj || new ChatPush()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatPush(bb:flatbuffers.ByteBuffer, obj?:ChatPush):ChatPush {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatPush()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

msgId():string|null
msgId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
msgId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

senderId():string|null
senderId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
senderId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

senderInfo(obj?:UserInfo):UserInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new UserInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

chatType():ChatType {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ChatType.UNKNOWN;
}

targetId():string|null
targetId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
targetId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

msgType():MsgType {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MsgType.UNKNOWN;
}

content():string|null
content(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
content(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sendTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

ext(index: number, obj?:KeyValue):KeyValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new KeyValue()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

extLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startChatPush(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addMsgId(builder:flatbuffers.Builder, msgIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, msgIdOffset, 0);
}

static addSenderId(builder:flatbuffers.Builder, senderIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, senderIdOffset, 0);
}

static addSenderInfo(builder:flatbuffers.Builder, senderInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, senderInfoOffset, 0);
}

static addChatType(builder:flatbuffers.Builder, chatType:ChatType) {
  builder.addFieldInt8(3, chatType, ChatType.UNKNOWN);
}

static addTargetId(builder:flatbuffers.Builder, targetIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, targetIdOffset, 0);
}

static addMsgType(builder:flatbuffers.Builder, msgType:MsgType) {
  builder.addFieldInt8(5, msgType, MsgType.UNKNOWN);
}

static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, contentOffset, 0);
}

static addSendTime(builder:flatbuffers.Builder, sendTime:bigint) {
  builder.addFieldInt64(7, sendTime, BigInt('0'));
}

static addExt(builder:flatbuffers.Builder, extOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, extOffset, 0);
}

static createExtVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startExtVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endChatPush(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
