// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ErrorCode } from '../../im/protocol/error-code.js';
import { ResponsePayload } from '../../im/protocol/response-payload.js';


export class ClientResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ClientResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClientResponse(bb:flatbuffers.ByteBuffer, obj?:ClientResponse):ClientResponse {
  return (obj || new ClientResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClientResponse(bb:flatbuffers.ByteBuffer, obj?:ClientResponse):ClientResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClientResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

reqId():string|null
reqId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
reqId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

code():ErrorCode {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : ErrorCode.SUCCESS;
}

msg():string|null
msg(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
msg(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

payloadType():ResponsePayload {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ResponsePayload.NONE;
}

payload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

payloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

payloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startClientResponse(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addReqId(builder:flatbuffers.Builder, reqIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, reqIdOffset, 0);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(1, timestamp, BigInt('0'));
}

static addCode(builder:flatbuffers.Builder, code:ErrorCode) {
  builder.addFieldInt16(2, code, ErrorCode.SUCCESS);
}

static addMsg(builder:flatbuffers.Builder, msgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, msgOffset, 0);
}

static addPayloadType(builder:flatbuffers.Builder, payloadType:ResponsePayload) {
  builder.addFieldInt8(4, payloadType, ResponsePayload.NONE);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, payloadOffset, 0);
}

static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endClientResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createClientResponse(builder:flatbuffers.Builder, reqIdOffset:flatbuffers.Offset, timestamp:bigint, code:ErrorCode, msgOffset:flatbuffers.Offset, payloadType:ResponsePayload, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientResponse.startClientResponse(builder);
  ClientResponse.addReqId(builder, reqIdOffset);
  ClientResponse.addTimestamp(builder, timestamp);
  ClientResponse.addCode(builder, code);
  ClientResponse.addMsg(builder, msgOffset);
  ClientResponse.addPayloadType(builder, payloadType);
  ClientResponse.addPayload(builder, payloadOffset);
  return ClientResponse.endClientResponse(builder);
}
}
