// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ErrorCode {
  SUCCESS = 0,
  UNKNOWN_ERROR = 1,
  AUTH_FAILED = 1001,
  PARAM_ERROR = 1002,
  ROOM_NOT_FOUND = 2001,
  ROOM_FULL = 2002,
  NOT_IN_ROOM = 2003
}
