// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class HeartbeatResp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HeartbeatResp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHeartbeatResp(bb:flatbuffers.ByteBuffer, obj?:HeartbeatResp):HeartbeatResp {
  return (obj || new HeartbeatResp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHeartbeatResp(bb:flatbuffers.ByteBuffer, obj?:HeartbeatResp):HeartbeatResp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HeartbeatResp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

serverTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startHeartbeatResp(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addServerTime(builder:flatbuffers.Builder, serverTime:bigint) {
  builder.addFieldInt64(0, serverTime, BigInt('0'));
}

static endHeartbeatResp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHeartbeatResp(builder:flatbuffers.Builder, serverTime:bigint):flatbuffers.Offset {
  HeartbeatResp.startHeartbeatResp(builder);
  HeartbeatResp.addServerTime(builder, serverTime);
  return HeartbeatResp.endHeartbeatResp(builder);
}
}
