// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MahjongColor } from '../../im/protocol/mahjong-color.js';


export class MahjongTile {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MahjongTile {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMahjongTile(bb:flatbuffers.ByteBuffer, obj?:MahjongTile):MahjongTile {
  return (obj || new MahjongTile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMahjongTile(bb:flatbuffers.ByteBuffer, obj?:MahjongTile):MahjongTile {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MahjongTile()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

color():MahjongColor {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MahjongColor.UNKNOWN;
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

index():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startMahjongTile(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addColor(builder:flatbuffers.Builder, color:MahjongColor) {
  builder.addFieldInt8(0, color, MahjongColor.UNKNOWN);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldInt32(1, value, 0);
}

static addIndex(builder:flatbuffers.Builder, index:number) {
  builder.addFieldInt32(2, index, 0);
}

static endMahjongTile(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMahjongTile(builder:flatbuffers.Builder, color:MahjongColor, value:number, index:number):flatbuffers.Offset {
  MahjongTile.startMahjongTile(builder);
  MahjongTile.addColor(builder, color);
  MahjongTile.addValue(builder, value);
  MahjongTile.addIndex(builder, index);
  return MahjongTile.endMahjongTile(builder);
}
}
