// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MahjongPushType {
  NONE = 0,
  GameStart = 1,
  TurnChange = 2,
  ActionResult = 3,
  AskAction = 4,
  Settlement = 5,
  TotalResult = 6
}
