// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MahjongAction } from '../../im/protocol/mahjong-action.js';
import { MahjongTile } from '../../im/protocol/mahjong-tile.js';


export class MahjongReq {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MahjongReq {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMahjongReq(bb:flatbuffers.ByteBuffer, obj?:MahjongReq):MahjongReq {
  return (obj || new MahjongReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMahjongReq(bb:flatbuffers.ByteBuffer, obj?:MahjongReq):MahjongReq {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MahjongReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

action():MahjongAction {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MahjongAction.DISCARD;
}

tile(obj?:MahjongTile):MahjongTile|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new MahjongTile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

eventId():string|null
eventId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
eventId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

decisionId():string|null
decisionId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
decisionId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startMahjongReq(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addAction(builder:flatbuffers.Builder, action:MahjongAction) {
  builder.addFieldInt8(0, action, MahjongAction.DISCARD);
}

static addTile(builder:flatbuffers.Builder, tileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, tileOffset, 0);
}

static addEventId(builder:flatbuffers.Builder, eventIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, eventIdOffset, 0);
}

static addDecisionId(builder:flatbuffers.Builder, decisionIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, decisionIdOffset, 0);
}

static endMahjongReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
