// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MahjongTile } from '../../im/protocol/mahjong-tile.js';
import { MeldType } from '../../im/protocol/meld-type.js';


export class MeldGroup {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MeldGroup {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMeldGroup(bb:flatbuffers.ByteBuffer, obj?:MeldGroup):MeldGroup {
  return (obj || new MeldGroup()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMeldGroup(bb:flatbuffers.ByteBuffer, obj?:MeldGroup):MeldGroup {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MeldGroup()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

meldType():MeldType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MeldType.PONG;
}

tiles(index: number, obj?:MahjongTile):MahjongTile|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new MahjongTile()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

fromSeat():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startMeldGroup(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addMeldType(builder:flatbuffers.Builder, meldType:MeldType) {
  builder.addFieldInt8(0, meldType, MeldType.PONG);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, tilesOffset, 0);
}

static createTilesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addFromSeat(builder:flatbuffers.Builder, fromSeat:number) {
  builder.addFieldInt32(2, fromSeat, 0);
}

static endMeldGroup(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMeldGroup(builder:flatbuffers.Builder, meldType:MeldType, tilesOffset:flatbuffers.Offset, fromSeat:number):flatbuffers.Offset {
  MeldGroup.startMeldGroup(builder);
  MeldGroup.addMeldType(builder, meldType);
  MeldGroup.addTiles(builder, tilesOffset);
  MeldGroup.addFromSeat(builder, fromSeat);
  return MeldGroup.endMeldGroup(builder);
}
}
