// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MahjongTile } from '../../im/protocol/mahjong-tile.js';
import { PlayerPublicInfo } from '../../im/protocol/player-public-info.js';


export class MjGameStart {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MjGameStart {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMjGameStart(bb:flatbuffers.ByteBuffer, obj?:MjGameStart):MjGameStart {
  return (obj || new MjGameStart()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMjGameStart(bb:flatbuffers.ByteBuffer, obj?:MjGameStart):MjGameStart {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MjGameStart()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

handTiles(index: number, obj?:MahjongTile):MahjongTile|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MahjongTile()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

handTilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

playersPublicInfo(index: number, obj?:PlayerPublicInfo):PlayerPublicInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new PlayerPublicInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

playersPublicInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

remainCards():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

dealerSeat():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startMjGameStart(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addHandTiles(builder:flatbuffers.Builder, handTilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, handTilesOffset, 0);
}

static createHandTilesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHandTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addPlayersPublicInfo(builder:flatbuffers.Builder, playersPublicInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, playersPublicInfoOffset, 0);
}

static createPlayersPublicInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPlayersPublicInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRemainCards(builder:flatbuffers.Builder, remainCards:number) {
  builder.addFieldInt32(2, remainCards, 0);
}

static addDealerSeat(builder:flatbuffers.Builder, dealerSeat:number) {
  builder.addFieldInt32(3, dealerSeat, 0);
}

static endMjGameStart(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMjGameStart(builder:flatbuffers.Builder, handTilesOffset:flatbuffers.Offset, playersPublicInfoOffset:flatbuffers.Offset, remainCards:number, dealerSeat:number):flatbuffers.Offset {
  MjGameStart.startMjGameStart(builder);
  MjGameStart.addHandTiles(builder, handTilesOffset);
  MjGameStart.addPlayersPublicInfo(builder, playersPublicInfoOffset);
  MjGameStart.addRemainCards(builder, remainCards);
  MjGameStart.addDealerSeat(builder, dealerSeat);
  return MjGameStart.endMjGameStart(builder);
}
}
