// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MahjongTile } from '../../im/protocol/mahjong-tile.js';


export class MjTurnChange {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MjTurnChange {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMjTurnChange(bb:flatbuffers.ByteBuffer, obj?:MjTurnChange):MjTurnChange {
  return (obj || new MjTurnChange()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMjTurnChange(bb:flatbuffers.ByteBuffer, obj?:MjTurnChange):MjTurnChange {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MjTurnChange()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

currentSeat():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

remainCards():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

countdown():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

drawnTile(obj?:MahjongTile):MahjongTile|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new MahjongTile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startMjTurnChange(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addCurrentSeat(builder:flatbuffers.Builder, currentSeat:number) {
  builder.addFieldInt32(0, currentSeat, 0);
}

static addRemainCards(builder:flatbuffers.Builder, remainCards:number) {
  builder.addFieldInt32(1, remainCards, 0);
}

static addCountdown(builder:flatbuffers.Builder, countdown:number) {
  builder.addFieldInt32(2, countdown, 0);
}

static addDrawnTile(builder:flatbuffers.Builder, drawnTileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, drawnTileOffset, 0);
}

static endMjTurnChange(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
