// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Platform {
  UNKNOWN = 0,
  ANDROID = 1,
  IOS = 2,
  WEB = 3,
  DESKTOP = 4,
  WECHAT = 5
}
