// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MahjongTile } from '../../im/protocol/mahjong-tile.js';
import { MeldGroup } from '../../im/protocol/meld-group.js';


export class PlayerPublicInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerPublicInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerPublicInfo(bb:flatbuffers.ByteBuffer, obj?:PlayerPublicInfo):PlayerPublicInfo {
  return (obj || new PlayerPublicInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerPublicInfo(bb:flatbuffers.ByteBuffer, obj?:PlayerPublicInfo):PlayerPublicInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerPublicInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

seat():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

userId():string|null
userId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
userId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

melds(index: number, obj?:MeldGroup):MeldGroup|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new MeldGroup()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

meldsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

discarded(index: number, obj?:MahjongTile):MahjongTile|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new MahjongTile()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

discardedLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

handCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startPlayerPublicInfo(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addSeat(builder:flatbuffers.Builder, seat:number) {
  builder.addFieldInt32(0, seat, 0);
}

static addUserId(builder:flatbuffers.Builder, userIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, userIdOffset, 0);
}

static addMelds(builder:flatbuffers.Builder, meldsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, meldsOffset, 0);
}

static createMeldsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMeldsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addDiscarded(builder:flatbuffers.Builder, discardedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, discardedOffset, 0);
}

static createDiscardedVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDiscardedVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addHandCount(builder:flatbuffers.Builder, handCount:number) {
  builder.addFieldInt32(4, handCount, 0);
}

static endPlayerPublicInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerPublicInfo(builder:flatbuffers.Builder, seat:number, userIdOffset:flatbuffers.Offset, meldsOffset:flatbuffers.Offset, discardedOffset:flatbuffers.Offset, handCount:number):flatbuffers.Offset {
  PlayerPublicInfo.startPlayerPublicInfo(builder);
  PlayerPublicInfo.addSeat(builder, seat);
  PlayerPublicInfo.addUserId(builder, userIdOffset);
  PlayerPublicInfo.addMelds(builder, meldsOffset);
  PlayerPublicInfo.addDiscarded(builder, discardedOffset);
  PlayerPublicInfo.addHandCount(builder, handCount);
  return PlayerPublicInfo.endPlayerPublicInfo(builder);
}
}
