// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RequestPayload {
  NONE = 0,
  ChatSendReq = 1,
  GameReq = 2,
  HeartbeatReq = 3,
  RoomReq = 4,
  ConversationReadReq = 5
}

