// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ResponsePayload {
  NONE = 0,
  ChatSendAck = 1,
  RoomResp = 2,
  HeartbeatResp = 3,
  ChatPush = 10,
  GamePush = 11,
  RoomPush = 12,
  SystemPush = 13
}
