// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GameType } from '../../im/protocol/game-type.js';
import { RoomAction } from '../../im/protocol/room-action.js';


export class RoomReq {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomReq {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomReq(bb:flatbuffers.ByteBuffer, obj?:RoomReq):RoomReq {
  return (obj || new RoomReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomReq(bb:flatbuffers.ByteBuffer, obj?:RoomReq):RoomReq {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

action():RoomAction {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : RoomAction.CREATE;
}

gameType():GameType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : GameType.UNKNOWN;
}

roomId():string|null
roomId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
roomId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

roomConfig():string|null
roomConfig(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
roomConfig(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startRoomReq(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addAction(builder:flatbuffers.Builder, action:RoomAction) {
  builder.addFieldInt8(0, action, RoomAction.CREATE);
}

static addGameType(builder:flatbuffers.Builder, gameType:GameType) {
  builder.addFieldInt8(1, gameType, GameType.UNKNOWN);
}

static addRoomId(builder:flatbuffers.Builder, roomIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, roomIdOffset, 0);
}

static addRoomConfig(builder:flatbuffers.Builder, roomConfigOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, roomConfigOffset, 0);
}

static endRoomReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomReq(builder:flatbuffers.Builder, action:RoomAction, gameType:GameType, roomIdOffset:flatbuffers.Offset, roomConfigOffset:flatbuffers.Offset):flatbuffers.Offset {
  RoomReq.startRoomReq(builder);
  RoomReq.addAction(builder, action);
  RoomReq.addGameType(builder, gameType);
  RoomReq.addRoomId(builder, roomIdOffset);
  RoomReq.addRoomConfig(builder, roomConfigOffset);
  return RoomReq.endRoomReq(builder);
}
}
