// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RoomEvent {
  USER_JOINED = 0,
  USER_LEFT = 1,
  USER_READY = 2,
  GAME_START = 3,
  GAME_OVER = 4,
  ROOM_DISMISSED = 5
}
