// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SystemLevel } from '../../im/protocol/system-level.js';


export class SystemPush {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SystemPush {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSystemPush(bb:flatbuffers.ByteBuffer, obj?:SystemPush):SystemPush {
  return (obj || new SystemPush()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSystemPush(bb:flatbuffers.ByteBuffer, obj?:SystemPush):SystemPush {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SystemPush()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

title():string|null
title(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
title(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

content():string|null
content(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
content(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

level():SystemLevel {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : SystemLevel.INFO;
}

actionUrl():string|null
actionUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
actionUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSystemPush(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addTitle(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, titleOffset, 0);
}

static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, contentOffset, 0);
}

static addLevel(builder:flatbuffers.Builder, level:SystemLevel) {
  builder.addFieldInt8(2, level, SystemLevel.INFO);
}

static addActionUrl(builder:flatbuffers.Builder, actionUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, actionUrlOffset, 0);
}

static endSystemPush(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSystemPush(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset, contentOffset:flatbuffers.Offset, level:SystemLevel, actionUrlOffset:flatbuffers.Offset):flatbuffers.Offset {
  SystemPush.startSystemPush(builder);
  SystemPush.addTitle(builder, titleOffset);
  SystemPush.addContent(builder, contentOffset);
  SystemPush.addLevel(builder, level);
  SystemPush.addActionUrl(builder, actionUrlOffset);
  return SystemPush.endSystemPush(builder);
}
}
