// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class UserInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UserInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUserInfo(bb:flatbuffers.ByteBuffer, obj?:UserInfo):UserInfo {
  return (obj || new UserInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUserInfo(bb:flatbuffers.ByteBuffer, obj?:UserInfo):UserInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UserInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userId():string|null
userId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
userId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

nickname():string|null
nickname(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nickname(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

avatar():string|null
avatar(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
avatar(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

level():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

coins():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startUserInfo(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addUserId(builder:flatbuffers.Builder, userIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, userIdOffset, 0);
}

static addNickname(builder:flatbuffers.Builder, nicknameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nicknameOffset, 0);
}

static addAvatar(builder:flatbuffers.Builder, avatarOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, avatarOffset, 0);
}

static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt32(3, level, 0);
}

static addCoins(builder:flatbuffers.Builder, coins:bigint) {
  builder.addFieldInt64(4, coins, BigInt('0'));
}

static endUserInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUserInfo(builder:flatbuffers.Builder, userIdOffset:flatbuffers.Offset, nicknameOffset:flatbuffers.Offset, avatarOffset:flatbuffers.Offset, level:number, coins:bigint):flatbuffers.Offset {
  UserInfo.startUserInfo(builder);
  UserInfo.addUserId(builder, userIdOffset);
  UserInfo.addNickname(builder, nicknameOffset);
  UserInfo.addAvatar(builder, avatarOffset);
  UserInfo.addLevel(builder, level);
  UserInfo.addCoins(builder, coins);
  return UserInfo.endUserInfo(builder);
}
}
