#!/bin/bash

# FlatBuffers TypeScript 代码生成脚本
# 需要先安装 flatc: brew install flatbuffers

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCHEMA_FILE="${SCRIPT_DIR}/message.fbs"
# flatc 会根据 namespace im.protocol 自动创建 im/protocol/ 子目录
# 输出到 src/，最终路径是 src/im/protocol/
TS_OUTPUT_DIR="${SCRIPT_DIR}/../project/desktop-web/src"

# 检查 flatc 是否安装
if ! command -v flatc &> /dev/null; then
    echo "错误: flatc 未安装"
    echo "请使用以下命令安装:"
    echo "  brew install flatbuffers"
    exit 1
fi

# 创建输出目录
mkdir -p "${TS_OUTPUT_DIR}"

# 清理旧的生成文件（只删除 FlatBuffers 自动生成的文件）
echo "🧹 清理旧的 FlatBuffers 生成文件..."
CLEAN_DIR="${TS_OUTPUT_DIR}/im/protocol"
if [ -d "${CLEAN_DIR}" ]; then
    # 只删除包含 "automatically generated by the FlatBuffers compiler" 的文件
    find "${CLEAN_DIR}" -name "*.ts" -type f -exec grep -l "automatically generated by the FlatBuffers compiler" {} \; | while read file; do
        echo "  删除: $(basename "$file")"
        rm -f "$file"
    done
fi

# 生成 TypeScript 代码
echo ""
echo "📦 生成 FlatBuffers TypeScript 代码..."
flatc --ts -o "${TS_OUTPUT_DIR}" "${SCHEMA_FILE}"

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ TypeScript 代码生成成功!"
    echo "📁 输出目录: ${TS_OUTPUT_DIR}"
    echo ""
    echo "📋 已生成的文件:"
    find "${CLEAN_DIR}" -maxdepth 1 -name "*.ts" -type f 2>/dev/null | sort | while read file; do
        echo "  - $(basename "$file")"
    done
    echo ""
    echo "✨ 完成！新增的协议字段:"
    echo "  - RoomAction.CHANGE_SEAT"
    echo "  - RoomAction.START_GAME"
    echo "  - RoomReq.target_seat_index"
else
    echo ""
    echo "❌ 代码生成失败"
    exit 1
fi
