#!/bin/bash

# FlatBuffers Go 代码生成脚本
# 需要先安装 flatc: brew install flatbuffers

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCHEMA_FILE="${SCRIPT_DIR}/message.fbs"
OUTPUT_DIR="${SCRIPT_DIR}/../project/access-go/pkg/flatbuf"

# 检查 flatc 是否安装
if ! command -v flatc &> /dev/null; then
    echo "错误: flatc 未安装"
    echo "请使用以下命令安装:"
    echo "  brew install flatbuffers"
    exit 1
fi

# 创建输出目录
mkdir -p "${OUTPUT_DIR}"

# 清理旧的生成文件（只删除 FlatBuffers 自动生成的文件）
echo "🧹 清理旧的 FlatBuffers 生成文件..."
if [ -d "${OUTPUT_DIR}" ]; then
    # 只删除包含 "automatically generated by the FlatBuffers compiler" 的 Go 文件
    find "${OUTPUT_DIR}" -name "*.go" -type f -exec grep -l "automatically generated by the FlatBuffers compiler" {} \; | while read file; do
        echo "  删除: $(basename "$file")"
        rm -f "$file"
    done
fi

# 生成 Go 代码
echo ""
echo "📦 生成 FlatBuffers Go 代码..."
flatc --go -o "${OUTPUT_DIR}" "${SCHEMA_FILE}"

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Go 代码生成成功!"
    echo "📁 输出目录: ${OUTPUT_DIR}"
    echo ""
    echo "📋 已生成的文件:"
    find "${OUTPUT_DIR}" -name "*.go" -type f 2>/dev/null | while read file; do
        echo "  - $(basename "$file")"
    done | head -20
else
    echo ""
    echo "❌ 代码生成失败"
    exit 1
fi
