// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum AckStatus {
  UNKNOWN = 0,
  ACCEPTED = 1,
  PERSISTED = 2
}
