// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AckStatus } from '../../im/protocol/ack-status.js';


export class ChatSendAck {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatSendAck {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatSendAck(bb:flatbuffers.ByteBuffer, obj?:ChatSendAck):ChatSendAck {
  return (obj || new ChatSendAck()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatSendAck(bb:flatbuffers.ByteBuffer, obj?:ChatSendAck):ChatSendAck {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatSendAck()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

msgId():string|null
msgId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
msgId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sendTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

status():AckStatus {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : AckStatus.ACCEPTED;
}

static startChatSendAck(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addMsgId(builder:flatbuffers.Builder, msgIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, msgIdOffset, 0);
}

static addSendTime(builder:flatbuffers.Builder, sendTime:bigint) {
  builder.addFieldInt64(1, sendTime, BigInt('0'));
}

static addStatus(builder:flatbuffers.Builder, status:AckStatus) {
  builder.addFieldInt8(2, status, AckStatus.ACCEPTED);
}

static endChatSendAck(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChatSendAck(builder:flatbuffers.Builder, msgIdOffset:flatbuffers.Offset, sendTime:bigint, status:AckStatus):flatbuffers.Offset {
  ChatSendAck.startChatSendAck(builder);
  ChatSendAck.addMsgId(builder, msgIdOffset);
  ChatSendAck.addSendTime(builder, sendTime);
  ChatSendAck.addStatus(builder, status);
  return ChatSendAck.endChatSendAck(builder);
}
}
