// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ChatType {
  UNKNOWN = 0,
  PRIVATE = 1,
  GROUP = 2,
  SYSTEM = 3,
  MAHJONG = 4
}
