// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GamePayload } from '../../im/protocol/game-payload.js';
import { GameType } from '../../im/protocol/game-type.js';


export class GameReq {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameReq {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameReq(bb:flatbuffers.ByteBuffer, obj?:GameReq):GameReq {
  return (obj || new GameReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameReq(bb:flatbuffers.ByteBuffer, obj?:GameReq):GameReq {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomId():string|null
roomId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
roomId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

gameType():GameType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : GameType.UNKNOWN;
}

gamePayloadType():GamePayload {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : GamePayload.NONE;
}

gamePayload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

gamePayloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

gamePayloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startGameReq(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addRoomId(builder:flatbuffers.Builder, roomIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, roomIdOffset, 0);
}

static addGameType(builder:flatbuffers.Builder, gameType:GameType) {
  builder.addFieldInt8(1, gameType, GameType.UNKNOWN);
}

static addGamePayloadType(builder:flatbuffers.Builder, gamePayloadType:GamePayload) {
  builder.addFieldInt8(2, gamePayloadType, GamePayload.NONE);
}

static addGamePayload(builder:flatbuffers.Builder, gamePayloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, gamePayloadOffset, 0);
}

static createGamePayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startGamePayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endGameReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameReq(builder:flatbuffers.Builder, roomIdOffset:flatbuffers.Offset, gameType:GameType, gamePayloadType:GamePayload, gamePayloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  GameReq.startGameReq(builder);
  GameReq.addRoomId(builder, roomIdOffset);
  GameReq.addGameType(builder, gameType);
  GameReq.addGamePayloadType(builder, gamePayloadType);
  GameReq.addGamePayload(builder, gamePayloadOffset);
  return GameReq.endGameReq(builder);
}
}
