// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class HeartbeatReq {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):HeartbeatReq {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHeartbeatReq(bb:flatbuffers.ByteBuffer, obj?:HeartbeatReq):HeartbeatReq {
  return (obj || new HeartbeatReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHeartbeatReq(bb:flatbuffers.ByteBuffer, obj?:HeartbeatReq):HeartbeatReq {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new HeartbeatReq()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clientTime():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startHeartbeatReq(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addClientTime(builder:flatbuffers.Builder, clientTime:bigint) {
  builder.addFieldInt64(0, clientTime, BigInt('0'));
}

static endHeartbeatReq(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHeartbeatReq(builder:flatbuffers.Builder, clientTime:bigint):flatbuffers.Offset {
  HeartbeatReq.startHeartbeatReq(builder);
  HeartbeatReq.addClientTime(builder, clientTime);
  return HeartbeatReq.endHeartbeatReq(builder);
}
}
