// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MahjongColor {
  UNKNOWN = 0,
  MAN = 1,
  SUO = 2,
  PIN = 3,
  HONORS = 4
}
