// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MahjongAction {
  DISCARD = 0,
  PONG = 1,
  KONG = 2,
  HU = 3,
  ZI_MO = 4,
  AUTO = 5,
  PASS = 6
}
