// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MahjongPushType } from '../../im/protocol/mahjong-push-type.js';


export class MahjongPush {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MahjongPush {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMahjongPush(bb:flatbuffers.ByteBuffer, obj?:MahjongPush):MahjongPush {
  return (obj || new MahjongPush()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMahjongPush(bb:flatbuffers.ByteBuffer, obj?:MahjongPush):MahjongPush {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MahjongPush()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

eventId():string|null
eventId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
eventId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

pushType():MahjongPushType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : MahjongPushType.NONE;
}

pushData(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

pushDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

pushDataArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startMahjongPush(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addEventId(builder:flatbuffers.Builder, eventIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, eventIdOffset, 0);
}

static addPushType(builder:flatbuffers.Builder, pushType:MahjongPushType) {
  builder.addFieldInt8(1, pushType, MahjongPushType.NONE);
}

static addPushData(builder:flatbuffers.Builder, pushDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, pushDataOffset, 0);
}

static createPushDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPushDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endMahjongPush(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMahjongPush(builder:flatbuffers.Builder, eventIdOffset:flatbuffers.Offset, pushType:MahjongPushType, pushDataOffset:flatbuffers.Offset):flatbuffers.Offset {
  MahjongPush.startMahjongPush(builder);
  MahjongPush.addEventId(builder, eventIdOffset);
  MahjongPush.addPushType(builder, pushType);
  MahjongPush.addPushData(builder, pushDataOffset);
  return MahjongPush.endMahjongPush(builder);
}
}
