// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MahjongAction } from '../../im/protocol/mahjong-action.js';
import { MahjongTile } from '../../im/protocol/mahjong-tile.js';


export class MjAskAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MjAskAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMjAskAction(bb:flatbuffers.ByteBuffer, obj?:MjAskAction):MjAskAction {
  return (obj || new MjAskAction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMjAskAction(bb:flatbuffers.ByteBuffer, obj?:MjAskAction):MjAskAction {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MjAskAction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

decisionId():string|null
decisionId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
decisionId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

countdown():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

triggerTile(obj?:MahjongTile):MahjongTile|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new MahjongTile()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

allowedActions(index: number):MahjongAction|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index) : null;
}

allowedActionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

allowedActionsArray():Int8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Int8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startMjAskAction(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addDecisionId(builder:flatbuffers.Builder, decisionIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, decisionIdOffset, 0);
}

static addCountdown(builder:flatbuffers.Builder, countdown:number) {
  builder.addFieldInt32(1, countdown, 0);
}

static addTriggerTile(builder:flatbuffers.Builder, triggerTileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, triggerTileOffset, 0);
}

static addAllowedActions(builder:flatbuffers.Builder, allowedActionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, allowedActionsOffset, 0);
}

static createAllowedActionsVector(builder:flatbuffers.Builder, data:MahjongAction[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startAllowedActionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endMjAskAction(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
