// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RoomEvent } from '../../im/protocol/room-event.js';
import { RoomInfo } from '../../im/protocol/room-info.js';


export class RoomPush {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomPush {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomPush(bb:flatbuffers.ByteBuffer, obj?:RoomPush):RoomPush {
  return (obj || new RoomPush()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomPush(bb:flatbuffers.ByteBuffer, obj?:RoomPush):RoomPush {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomPush()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

event():RoomEvent {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : RoomEvent.USER_JOINED;
}

roomId():string|null
roomId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
roomId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

userId():string|null
userId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
userId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

roomInfo(obj?:RoomInfo):RoomInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new RoomInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startRoomPush(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addEvent(builder:flatbuffers.Builder, event:RoomEvent) {
  builder.addFieldInt8(0, event, RoomEvent.USER_JOINED);
}

static addRoomId(builder:flatbuffers.Builder, roomIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, roomIdOffset, 0);
}

static addUserId(builder:flatbuffers.Builder, userIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, userIdOffset, 0);
}

static addRoomInfo(builder:flatbuffers.Builder, roomInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, roomInfoOffset, 0);
}

static endRoomPush(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
