// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RoomInfo } from '../../im/protocol/room-info.js';


export class RoomResp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomResp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomResp(bb:flatbuffers.ByteBuffer, obj?:RoomResp):RoomResp {
  return (obj || new RoomResp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomResp(bb:flatbuffers.ByteBuffer, obj?:RoomResp):RoomResp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomResp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomId():string|null
roomId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
roomId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

roomInfo(obj?:RoomInfo):RoomInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new RoomInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startRoomResp(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addRoomId(builder:flatbuffers.Builder, roomIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, roomIdOffset, 0);
}

static addRoomInfo(builder:flatbuffers.Builder, roomInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, roomInfoOffset, 0);
}

static endRoomResp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
