// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RoomPlayer } from '../../im/protocol/room-player.js';
import { RoomStatus } from '../../im/protocol/room-status.js';


export class RoomInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomInfo(bb:flatbuffers.ByteBuffer, obj?:RoomInfo):RoomInfo {
  return (obj || new RoomInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomInfo(bb:flatbuffers.ByteBuffer, obj?:RoomInfo):RoomInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomId():string|null
roomId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
roomId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

ownerId():string|null
ownerId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ownerId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

maxPlayers():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

currentPlayers():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

players(index: number, obj?:RoomPlayer):RoomPlayer|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new RoomPlayer()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

playersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

status():RoomStatus {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : RoomStatus.WAITING;
}

static startRoomInfo(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addRoomId(builder:flatbuffers.Builder, roomIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, roomIdOffset, 0);
}

static addOwnerId(builder:flatbuffers.Builder, ownerIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, ownerIdOffset, 0);
}

static addMaxPlayers(builder:flatbuffers.Builder, maxPlayers:number) {
  builder.addFieldInt32(2, maxPlayers, 0);
}

static addCurrentPlayers(builder:flatbuffers.Builder, currentPlayers:number) {
  builder.addFieldInt32(3, currentPlayers, 0);
}

static addPlayers(builder:flatbuffers.Builder, playersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, playersOffset, 0);
}

static createPlayersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPlayersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStatus(builder:flatbuffers.Builder, status:RoomStatus) {
  builder.addFieldInt8(5, status, RoomStatus.WAITING);
}

static endRoomInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomInfo(builder:flatbuffers.Builder, roomIdOffset:flatbuffers.Offset, ownerIdOffset:flatbuffers.Offset, maxPlayers:number, currentPlayers:number, playersOffset:flatbuffers.Offset, status:RoomStatus):flatbuffers.Offset {
  RoomInfo.startRoomInfo(builder);
  RoomInfo.addRoomId(builder, roomIdOffset);
  RoomInfo.addOwnerId(builder, ownerIdOffset);
  RoomInfo.addMaxPlayers(builder, maxPlayers);
  RoomInfo.addCurrentPlayers(builder, currentPlayers);
  RoomInfo.addPlayers(builder, playersOffset);
  RoomInfo.addStatus(builder, status);
  return RoomInfo.endRoomInfo(builder);
}
}
