// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RoomAction {
  CREATE = 0,
  JOIN = 1,
  LEAVE = 2,
  READY = 3,
  CHANGE_SEAT = 4,
  START_GAME = 5
}
